//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncabezadoImp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncabezadoImp()
        {
            this.DetalleImp = new HashSet<DetalleImp>();
        }
    
        public int Id { get; set; }
        public string Moneda { get; set; }
        public System.DateTime Fecha_Transmision { get; set; }
        public string CodBanco { get; set; }
        public string RNC_Empresa { get; set; }
        public int MesPago { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleImp> DetalleImp { get; set; }
        public virtual Moneda MonedaEntity { get; set; }
    }
}
