//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTSS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISO810P1Entities : DbContext
    {
        public ISO810P1Entities()
            : base("name=ISO810P1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DetalleImp> DetalleImp { get; set; }
        public virtual DbSet<EncabezadoImp> EncabezadoImp { get; set; }
        public virtual DbSet<Moneda> Moneda { get; set; }
    }
}
